### ISSUE TITLE
Add a context menu to load quickly import the data 

### ISSUE THREAD

**Issue by GiulioRomualdi** [ami-iit/robot-log-visualizer#18]
Adding a right-click action on each item to quickly import the data in the console (see answer 3 in https://www.qtcentre.org/threads/18929-QTreeWidgetItem-have-contextMenu on how to add a context menu)

**Comment by GiulioRomualdi** [comment]
The mat file can be drag and dropped into the app

**Comment by traversaro** [comment]
Cool, i had no idea. Could it make sense to mention this in the readme?

**Comment by GiulioRomualdi** [comment]
Implemented in https://github.com/ami-iit/robot-log-visualizer/pull/74
