### ISSUE TITLE
Draw an icon for the application

### ISSUE THREAD

**Issue by GiulioRomualdi** [ami-iit/robot-log-visualizer#22]
It would be nice to have an icon for the application. 

cc @Giulero @isorrentino @paolo-viceconte

**Comment by GiulioRomualdi** [comment]
A temporary icon has been added in 370252fd57d01a363b913e3eff00a14a908071d1

**Comment by DanielePucci** [comment]
Cool icon @S-Dafarra !

**Comment by S-Dafarra** [comment]
I think the one @GiulioRomualdi actually picked is cooler though :wink: 

![Imm](https://raw.githubusercontent.com/ami-iit/robot-log-visualizer/370252fd57d01a363b913e3eff00a14a908071d1/ui/misc/icon.png)
