### ISSUE TITLE
Robot visualization non syncronized with data

### ISSUE THREAD

**Issue by carloscp3009** [ami-iit/robot-log-visualizer#71]
The data plot in the visualizer is not syncronized in the time axes with the motion of the robot visualizer. Attached there is a video that shows the signal of the knee that match the motion of the robot in the jabra but not in the visualizer. 
Note: In the video, the time axes was already modify with the intention of fixing the problem, in the original configuration the robot visualizer only move the fingers.
There is also attached the data used in the video. 

[Screencast from 14-11-2023 19:44:19.webm](https://github.com/ami-iit/robot-log-visualizer/assets/44415073/115f095a-3b36-44ea-b996-e5db6ace688f)

https://istitutoitalianotecnologia-my.sharepoint.com/:u:/g/personal/carlos_cardenas_iit_it/EY4zNd52uiFGqd5npTz7qaABj57lbA1MOIjUSBFbGp5wmg?e=bpes7g

**Comment by DanielePucci** [comment]
CC @GiulioRomualdi @paolo-viceconte

**Comment by GiulioRomualdi** [comment]
Thank you, @carloscp3009, for reporting! I think the issue was there since the beginning. If you want you canctry to fix the problem, otherwise I'll try to give it a look in the week.

**Comment by GiulioRomualdi** [comment]
Fixed by https://github.com/ami-iit/robot-log-visualizer/pull/72

**Comment by carloscp3009** [comment]
Thanks @GiulioRomualdi for your help. I tested and it seems to be working right!
